### ISSUE TITLE
Include visual description of column attributes

### ISSUE THREAD

**Issue by jeroiraz** [codenotary/immudb-webconsole#3]
**What would you like to be added or enhanced**

When listing the columns of a table it would be great to visually identify which column is designed as primary key, which columns has been indexed and which columns are nullable.

**Why is this needed**

It will provide a complete description of the table, making it easier to identify its definition

**Additional context**

**Comment by Hextar** [comment]
That feature is now merged on master (commit: 1185adf)

![image](https://user-images.githubusercontent.com/8740725/123430435-76e7a480-d5c8-11eb-897a-72f225c15eb4.png)
